### ISSUE TITLE
Download data for exposure

### ISSUE THREAD

**Issue by Bekele-EMI** [icpac-igad/ibf-workshop#1]
Where I download data for exposure

**Comment by nishadhka** [comment]
Hi Bekele, please try this link to download the exposure data https://igadint-my.sharepoint.com/:f:/g/personal/nishadh_kalladath_igad_int/EnB3ZBxYKYlEqcyO6BVtJVcBcYY1EGsE8UWPjm91fKpaJg?e=Im8gbr

**Comment by Bekele-EMI** [comment]
Well received,Thank you very much!!

*********


*Bekele Kebebe Meteorologist (M.Sc. in Climate Change and Sustainable
Agriculture)*

*Ethiopia** Meteorology Institute*

*Numerical Weather Prediction Case Team*



*mobile: +251924867101 ***@***.*** ***@***.***>
Addis Ababa*

*Ethiopia*
